/* Florencia a pie: reconstructs the integrated audio from static text chunks. */
'use strict';
const SHELL='florencia-shell-chunked-v2';
const AUDIO='florencia-audio-v2';
const base=new URL('./',self.location.href);const url=p=>new URL(p,base).href;
const audioURL=url('assets/florencia.ogg');
const AUDIO_PARTS=46;
const FILES=["./","index.html","manifest.webmanifest","payload/site-000.b64","payload/site-001.b64","payload/site-002.b64","payload/audio-000.b64","payload/audio-001.b64","payload/audio-002.b64","payload/audio-003.b64","payload/audio-004.b64","payload/audio-005.b64","payload/audio-006.b64","payload/audio-007.b64","payload/audio-008.b64","payload/audio-009.b64","payload/audio-010.b64","payload/audio-011.b64","payload/audio-012.b64","payload/audio-013.b64","payload/audio-014.b64","payload/audio-015.b64","payload/audio-016.b64","payload/audio-017.b64","payload/audio-018.b64","payload/audio-019.b64","payload/audio-020.b64","payload/audio-021.b64","payload/audio-022.b64","payload/audio-023.b64","payload/audio-024.b64","payload/audio-025.b64","payload/audio-026.b64","payload/audio-027.b64","payload/audio-028.b64","payload/audio-029.b64","payload/audio-030.b64","payload/audio-031.b64","payload/audio-032.b64","payload/audio-033.b64","payload/audio-034.b64","payload/audio-035.b64","payload/audio-036.b64","payload/audio-037.b64","payload/audio-038.b64","payload/audio-039.b64","payload/audio-040.b64","payload/audio-041.b64","payload/audio-042.b64","payload/audio-043.b64","payload/audio-044.b64","payload/audio-045.b64"].map(url);
self.addEventListener('install',event=>event.waitUntil(caches.open(SHELL).then(c=>c.addAll(FILES)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('florencia-shell-')&&k!==SHELL).map(k=>caches.delete(k)));await Promise.all(keys.filter(k=>k.startsWith('florencia-audio-')&&k!==AUDIO).map(k=>caches.delete(k)));await self.clients.claim();})()));
async function textPart(path){const shell=await caches.open(SHELL);const u=url(path);const cached=await shell.match(u);const response=cached||await fetch(u);if(!response.ok)throw new Error('Missing '+path);return response.text();}
async function fullAudio(){const cache=await caches.open(AUDIO);const stored=await cache.match(audioURL);if(stored)return stored;const names=Array.from({length:AUDIO_PARTS},(_,i)=>`payload/audio-${String(i).padStart(3,'0')}.b64`);const parts=await Promise.all(names.map(textPart));const raw=atob(parts.join(''));const bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));const headers={'Content-Type':'audio/ogg','Content-Length':String(bytes.length),'Accept-Ranges':'bytes','Cache-Control':'public,max-age=31536000,immutable'};const response=new Response(bytes,{status:200,headers});await cache.put(audioURL,response.clone());return response;}
async function audioResponse(request){const full=await fullAudio();const range=request.headers.get('Range');if(!range)return full;const blob=await full.blob(),size=blob.size,match=/^bytes=(\d*)-(\d*)$/.exec(range.trim());const invalid=()=>new Response(null,{status:416,headers:{'Content-Range':`bytes */${size}`,'Accept-Ranges':'bytes'}});if(!match||(!match[1]&&!match[2]))return invalid();let start,end;if(!match[1]){const suffix=Number(match[2]);if(!Number.isSafeInteger(suffix)||suffix<=0)return invalid();start=Math.max(0,size-suffix);end=size-1;}else{start=Number(match[1]);end=match[2]?Math.min(Number(match[2]),size-1):size-1;}if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start<0||start>=size||end<start)return invalid();return new Response(blob.slice(start,end+1),{status:206,statusText:'Partial Content',headers:{'Content-Type':'audio/ogg','Content-Length':String(end-start+1),'Content-Range':`bytes ${start}-${end}/${size}`,'Accept-Ranges':'bytes'}});}
self.addEventListener('fetch',event=>{const request=event.request,u=new URL(request.url);if(request.method!=='GET'||u.origin!==base.origin||!u.pathname.startsWith(base.pathname))return;if(u.href===audioURL){event.respondWith(audioResponse(request));return;}event.respondWith((async()=>{const shell=await caches.open(SHELL);const cached=await shell.match(request);if(cached)return cached;try{const response=await fetch(request);if(response.ok&&u.pathname.startsWith(base.pathname))shell.put(request,response.clone());return response;}catch(err){if(request.mode==='navigate')return shell.match(url('index.html'));throw err;}})());});
